# Generated by Django 4.1 on 2022-09-15 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0018_setgroup_kaatsu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setgroup',
            name='kaatsu',
        ),
    ]
