# Generated by Django 4.1 on 2022-09-16 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0025_setgroup_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscription',
            field=models.CharField(default='A', max_length=2),
            preserve_default=False,
        ),
    ]
